# template for traffic parameters file
gp:
  num_individuals: 1
  generations: 1
  multi_island:
    num_islands: 1
    migration: { "freq": 10, "frac": 0.05 }
  crossover_prob: 0.
  mut_prob: 0.
  frac_elitist: 0
  min_: 2
  max_: 4
  overlapping_generation: True
  validate: False
  penalty: { "method": "length", "reg_param": 0.01}
  select:
    fun: random.sample
    kargs: "{'k': self.num_individuals}"
  mutate:
    fun: gp.mixedMutate
    kargs: "{'expr': toolbox.expr_mut, 'pset': pset, 'prob': [0.7, 0.2, 0.1]}"
    expr_mut: gp.genHalfAndHalf
    expr_mut_kargs: "{'min_': 2, 'max_': 4, 'max_length': 20}"
  crossover:
    fun: gp.cxOnePoint
    kargs: "{}"
  immigration: { "enabled": False, "freq": 10, "frac": 0.9 }
  primitives:
    imports: { "flex.gp.cochain_primitives": ["coch_primitives"],
              "flex.gp.jax_primitives": ["jax_primitives"]} 
    used:  [
    {"name": "AddF", "dimension": None, "rank": None},
    {"name": "SubF", "dimension": None, "rank": None},
    {"name": "MulF", "dimension": None, "rank": None},
    {"name": "Div", "dimension": None, "rank": None},
    {"name": "SquareF", "dimension": None, "rank": None},
    {"name": "SqrtF", "dimension": None, "rank": None},
    {"name": "ExpF", "dimension": None, "rank": None},
    #{"name": "LogF", "dimension": None, "rank": None},
    {"name": "AddC", "dimension": ["0", "1"], "rank": ["SC"]},
    {"name": "SubC", "dimension": ["0", "1"], "rank": ["SC"]},
    {"name": "Square", "dimension": ["0", "1"], "rank": ["SC"]},
    {"name": "Sqrt", "dimension": ["0", "1"], "rank": ["SC"]},
    {"name": "MF", "dimension": ["0", "1"], "rank": ["SC"]},
    {"name": "Exp", "dimension": ["0", "1"], "rank": ["SC"]},
    #{"name": "Log", "dimension": ["0", "1"], "rank": ["SC"]},
    { "name": "cob", "dimension": ["0"], "rank": ["SC"] },
    { "name": "del", "dimension": ["1"], "rank": ["SC"] },
    { "name": "St1", "dimension": ["0", "1"], "rank": ["SC"] },
    #{ "name": "InvM", "dimension": ["0", "1"], "rank": ["SC"] },
    { "name": "CMul", "dimension": ["0", "1"], "rank": ["SC"] },
    #{ "name": "Inn", "dimension": ["0", "1"], "rank": ["SC"] },
  ]
  num_cpus: 1
  batch_size: 1
  max_calls: 2
  set_seed: True
  road_name: "US80"
  task: "prediction"
  ansatz: {"flux": triangular_flux, "v": triangular_v, "opt_coeffs":  [0.37013956, 1.48964708, 6.59672108]}
  # ansatz: {"flux": IDM_flux, "v": inverse_IDM, "opt_coeffs": [0.13046561, 0.74381154, 0.05752636, 0.54561196]}